import Head from "next/head";
import Image from "next/image";
import backgroundImage from "../public/background.webp";

export default function Home() {
  function toggle_hidden() {
    document.getElementById("modal").remove();
    console.log("pressed");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center h-screen w-screen items-center">
        <div className="fixed h-screen w-screen">
          <Image src={backgroundImage} alt="backgound image" fill priority />
        </div>
        <div
          id="modal"
          className={
            "flex gap-2 items-center  justify-center bg-sky-400 text-black z-10 rounded-md p-2 "
          }
        >
          <div className="flex flex-col">
            <p className="font-bold text-md">Find these Super heros:</p>
            <h1 className="text-lg">1- Iron Man</h1>
            <h1 className="text-lg">2- The Hulk</h1>
            <h1 className="text-lg">3- Batman</h1>
          </div>
          <button
            onClick={toggle_hidden}
            className="bg-cyan-100 p-2 rounded self-end"
          >
            Play!
          </button>
        </div>
      </div>
    </>
  );
}
